"""
Ensemble Disagreement for Hallucination Detection
===================================================

Extracts factual claims from answers generated by two different Groq models
and checks for NLI contradictions between claim pairs. A higher
contradiction rate signals factual uncertainty / hallucination.

Uses the local NLI model (``microsoft/deberta-large-mnli``) via the
synchronous ``nli.contradicts`` helper.
"""

from __future__ import annotations

import asyncio
import logging
import time
import re
from typing import Optional

from groq import Groq

from src.config import get_settings
from src.verification import nli

logger = logging.getLogger(__name__)


def strip_think_tags(text: str) -> str:
    """Remove <think>...</think> reasoning blocks from Qwen/DeepSeek models."""
    cleaned = re.sub(r'<think>.*?(?:</think>|$)', '', text, flags=re.DOTALL)
    return cleaned.strip()


# ── Claim Extraction ─────────────────────────────────────────────────────────


def extract_claims(
    text: str,
    model: Optional[str] = None,
) -> list[str]:
    """Extract factual claims from the given text using a Groq model.

    Parameters
    ----------
    text : str
        The text to extract claims from.
    model : str | None
        Groq model to use (defaults to ``PRIMARY_MODEL``).

    Returns
    -------
    list[str]
        A list of individual factual claim strings.
    """
    settings = get_settings()
    model = model or settings.primary_model

    client = Groq(api_key=settings.groq_api_key)
    prompt = (
        "List the factual claims made in the following text, one per line. "
        "Do not include any introductory or concluding text, just the claims. "
        "Extract every factual statement, even if it is a well-known or obvious fact:\n\n"
        f"{text}"
    )
    try:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.1,
            max_tokens=4096,
        )
        content = response.choices[0].message.content.strip()
        logger.warning("RAW EXTRACTED CLAIMS: %s", content)
        content = strip_think_tags(content)
    except Exception as e:
        logger.warning("Failed to extract claims: %s", e)
        content = ""
        
    claims = [
        line.strip().lstrip("-*1234567890. ")
        for line in content.split("\n")
        if line.strip()
    ]
    if not claims:
        claims = ["Model provided no factual claims."]
    logger.info("Extracted %d claims from text (%d chars)", len(claims), len(text))
    return claims


# ── Ensemble Disagreement ────────────────────────────────────────────────────


def compute_ensemble_disagreement(
    prompt: str,
    model1: Optional[str] = None,
    model2: Optional[str] = None,
) -> dict:
    """Compute ensemble disagreement between two models.

    Steps:
    1. Generate one answer from each model.
    2. Extract factual claims from both answers.
    3. Check all claim pairs for NLI contradictions (async, parallelized).
    4. Return contradiction ratio and details.

    Parameters
    ----------
    prompt : str
        The question to answer.
    model1 : str | None
        First Groq model (defaults to ``PRIMARY_MODEL``).
    model2 : str | None
        Second Groq model (defaults to ``SECONDARY_MODEL``).

    Returns
    -------
    dict
        Keys: ``disagreement_score``, ``model1_answer``, ``model2_answer``,
        ``model1_claims``, ``model2_claims``, ``contradictions_found``,
        ``total_claim_pairs``.
    """
    settings = get_settings()
    model1 = model1 or settings.primary_model
    model2 = model2 or settings.secondary_model

    client = Groq(api_key=settings.groq_api_key)

    logger.info("Ensemble disagreement: generating answers from %s and %s", model1, model2)

    # Generate answer from model 1
    ans1 = ""
    for _ in range(3):
        try:
            resp1 = client.chat.completions.create(
                model=model1,
                messages=[
                    {"role": "system", "content": "Answer the user's question comprehensively in 2-4 sentences, including as many specific factual details as possible."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
                max_tokens=2048,
            )
            ans1 = strip_think_tags((resp1.choices[0].message.content or "").strip())
        except Exception as e:
            logger.warning("Model 1 gen attempt failed: %s", e)
            ans1 = ""
        if len(ans1) > 5: break
        time.sleep(1.0)
    
    if not ans1 or len(ans1) <= 5:
        logger.warning("Model 1 (%s) failed or returned empty. Falling back to Model 2.", model1)
        for _ in range(3):
            try:
                resp1 = client.chat.completions.create(
                    model=model2,
                    messages=[
                        {"role": "system", "content": "Answer the user's question comprehensively in 2-4 sentences, including as many specific factual details as possible."},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.1,  # Lower temp to distinguish from ans2
                    max_tokens=2048,
                )
                ans1 = strip_think_tags((resp1.choices[0].message.content or "").strip())
            except Exception as e:
                logger.warning("Model 1 fallback attempt failed: %s", e)
                ans1 = ""
            if len(ans1) > 5: break
            time.sleep(1.0)
            
    if not ans1 or len(ans1) <= 5:
        ans1 = "Error: Failed to generate response from primary model."

    time.sleep(1.0)

    # Generate answer from model 2
    ans2 = ""
    for _ in range(3):
        try:
            resp2 = client.chat.completions.create(
                model=model2,
                messages=[
                    {"role": "system", "content": "Answer the user's question comprehensively in 2-4 sentences, including as many specific factual details as possible."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,
                max_tokens=2048,
            )
            ans2 = strip_think_tags((resp2.choices[0].message.content or "").strip())
        except Exception as e:
            logger.warning("Model 2 gen attempt failed: %s", e)
            ans2 = ""
        if len(ans2) > 5: break
        time.sleep(1.0)

    if not ans2 or len(ans2) <= 5:
        logger.warning("Model 2 (%s) failed or returned empty. Retrying with higher temp.", model2)
        for _ in range(3):
            try:
                resp2 = client.chat.completions.create(
                    model=model2,
                    messages=[
                        {"role": "system", "content": "Answer the user's question comprehensively in 2-4 sentences, including as many specific factual details as possible."},
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.8,  # Higher temp to ensure a different answer
                    max_tokens=2048,
                )
                ans2 = strip_think_tags((resp2.choices[0].message.content or "").strip())
            except Exception as e:
                logger.warning("Model 2 retry attempt failed: %s", e)
                ans2 = ""
            if len(ans2) > 5: break
            time.sleep(1.0)
            
    if not ans2 or len(ans2) <= 5:
        ans2 = "Error: Failed to generate response from secondary model."
            
    logger.warning("DEBUG ans1 (Model 1): %s", ans1)
    logger.warning("DEBUG ans2 (Model 2): %s", ans2)
    time.sleep(1.0)

    # Extract claims
    if not ans1 or len(ans1) <= 5:
        claims1 = ["Model provided no factual claims."]
    else:
        claims1 = extract_claims(ans1, model=model2)[:5]  # Limit to 5 claims
        
    time.sleep(1.0)
    
    if not ans2 or len(ans2) <= 5:
        claims2 = ["Model provided no factual claims."]
    else:
        claims2 = extract_claims(ans2, model=model2)[:5]  # Limit to 5 claims

    if not claims1 or not claims2:
        logger.info("No claims extracted — disagreement score = 0")
        return {
            "disagreement_score": 0.0,
            "model1_answer": ans1,
            "model2_answer": ans2,
            "model1_claims": claims1,
            "model2_claims": claims2,
            "contradictions_found": 0,
            "total_claim_pairs": 0,
        }

    # Check all claim pairs for contradictions (async + parallel)
    logger.info("Comparing %d × %d claim pairs for contradictions",
                len(claims1), len(claims2))

    def check_contradiction(c1: str, c2: str) -> bool:
        """True only if BOTH directions contradict — eliminates false positives
        from NLI treating unrelated-topic pairs as contradictions."""
        return nli.contradicts(c1, c2) and nli.contradicts(c2, c1)

    contradictions = 0
    total_pairs = len(claims1) * len(claims2)

    results = []
    for c1 in claims1:
        for c2 in claims2:
            try:
                results.append(check_contradiction(c1, c2))
            except Exception as e:
                results.append(e)

    for result in results:
        if isinstance(result, Exception):
            logger.warning("Contradiction check failed: %s", result)
            continue
        if result:
            contradictions += 1

    disagreement_score = contradictions / total_pairs if total_pairs > 0 else 0.0

    logger.info("Ensemble disagreement: %d contradictions / %d pairs = %.2f%%",
                contradictions, total_pairs, disagreement_score * 100)

    return {
        "disagreement_score": disagreement_score,
        "model1_answer": ans1,
        "model2_answer": ans2,
        "model1_claims": claims1,
        "model2_claims": claims2,
        "contradictions_found": contradictions,
        "total_claim_pairs": total_pairs,
    }
